/*Generated by Xtext*/
package msi.gama.lang.gaml.web.contentassist

import msi.gama.lang.gaml.web.contentassist.AbstractGamlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class GamlProposalProvider1 extends AbstractGamlProposalProvider {
}
