/**
 * @Generated by DSLFORGE
 */
package msi.gama.lang.gaml.web.editor;

public class GamlActionBarContributor extends AbstractGamlActionBarContributor {

	public GamlActionBarContributor() {
		super();
	}
}
