/**
 * @Generated by DSLFORGE
 */
package msi.gama.lang.gaml.web.editor.participative;

import msi.gama.lang.gaml.web.editor.AbstractGamlActionBarContributor;

public class EtherPadActionBarContributor extends AbstractGamlActionBarContributor {

	public EtherPadActionBarContributor() {
		super();
	}
}
