# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Github Travis

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:  # For manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 15 

      - name: Prepare build
        run: |
          echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=1024m'" >> ~/.mavenrc
          sudo apt install sshpass -y
          sudo chmod +x $GITHUB_WORKSPACE/*.sh          
 
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
 
      - name: Compile with Maven
        shell: bash
        run: $GITHUB_WORKSPACE/compile.sh 
        env:
          MSG: ${ github.event.head_commit.message }
          HQN_TOKEN: ${{ secrets.HQN_TOKEN }}
          TRAVIS_COMMIT: ${ GITHUB_SHA }
          TRAVIS_EVENT_TYPE: ${{ github.event_name }}

      - name: Publish to Github
        shell: bash
        run: $GITHUB_WORKSPACE/publish.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SSHPASS: ${{ secrets.USER_PWD }}
          BOT_TOKEN: ${{ secrets.GAMA_BOT_TOKEN }}
          TRAVIS_COMMIT: ${ GITHUB_SHA }
          TRAVIS_EVENT_TYPE: ${{ github.event_name }}